#!/bin/bash
# Linux Server Inspection Script
# Generated by OneOps Script Studio

LOG_DIR="/var/log/server_inspect"
LOG_FILE="${LOG_DIR}/inspect_$(date +%Y%m%d_%H%M%S).log"
mkdir -p "$LOG_DIR"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

log "========== 开始系统巡检 =========="

# 1. 基础信息
log "--- 1. 基础信息 ---"
log "主机名: $(hostname)"
log "操作系统: $(cat /etc/os-release | grep PRETTY_NAME | cut -d= -f2 | tr -d '\"')"
log "内核版本: $(uname -r)"
log "运行时间: $(uptime -p)"

# 2. CPU 负载
log "--- 2. CPU 负载 ---"
log "负载 (1/5/15分钟): $(cat /proc/loadavg | awk '{print $1, $2, $3}')"
log "CPU 核心数: $(nproc)"

# 3. 内存使用
log "--- 3. 内存使用 ---"
free -h | awk '/Mem:/ {printf "总计: %s, 已用: %s, 可用: %s, 使用率: %s\n", $2, $3, $7, $3/$2*100"%"}'

# 4. 磁盘使用
log "--- 4. 磁盘使用 ---"
df -h | awk 'NR>1 {printf "挂载点: %-10s 大小: %-8s 已用: %-8s 可用: %-8s 使用率: %s\n", $6, $2, $3, $4, $5}'

# 5. 网络状态
log "--- 5. 网络状态 ---"
ip addr show | grep -E "inet " | awk '{print $2}' | head -n 5
ss -tuln | head -n 10

# 6. 资源占用 Top 5
log "--- 6. 资源占用 Top 5 (CPU) ---"
ps aux --sort=-%cpu | head -n 6
log "--- 7. 资源占用 Top 5 (内存) ---"
ps aux --sort=-%mem | head -n 6

log "========== 巡检完成 =========="
log "日志文件: $LOG_FILE"